<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MultiplayerChat.Contracts</AssemblyName>
    <RootNamespace>MultiplayerChat.Contracts</RootNamespace>
    <Version>1.0.0</Version>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net472</TargetFramework>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
